import React from "react";
import { FileText, ImageIcon, Code2, QrCode, Palette, Scissors, Minimize2, RefreshCw, AlignJustify, Lock, ScanLine, Wand2, Table, ShieldCheck, MessageSquare, Share2, Link, Terminal, Video, Mic, Type, Activity } from "lucide-react";

export type Tool = {
  title: string;
  description: string;
  seoTitle?: string;
  seoDescription?: string;
  href: string;
  iconName: string;
  category: string;
  bgClass: string;
  borderClass: string;
  keywords?: string[];
  proOnly?: boolean;
  comingSoon?: boolean;
  createdAt?: string;
};

export const ALL_TOOLS: Tool[] = [
  // PDF Tools
  { title: "Merge PDF", description: "Combine multiple PDFs into a single file.", seoTitle: "Merge PDF Online - Combine Multiple PDFs for Free", seoDescription: "Combine multiple PDF files into one professional document instantly. Toollix provides a fast, secure, and easy-to-use PDF merger that works in your browser with zero quality loss and no sign-up required.", href: "/tools/merge-pdf", iconName: "FileText", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["merge pdf", "combine pdf", "join pdf", "combine pdf files online", "free pdf merger"] },
  { title: "Split PDF", description: "Extract pages from any PDF.", seoTitle: "Split PDF Online - Extract Pages from PDF Easily", seoDescription: "Extract specific pages or split a PDF into separate files with precision and speed. Our free online PDF splitter is secure, fast, and preserves the original quality of your documents without any installation.", href: "/tools/split-pdf", iconName: "Scissors", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["split pdf", "extract pdf pages", "separate pdf pages", "pdf splitter online", "free pdf separator"] },
  { title: "Compress PDF", description: "Reduce PDF size effortlessly.", seoTitle: "Compress PDF Online - Reduce File Size without Quality Loss", seoDescription: "Shrink large PDF files for easier sharing while maintaining high document resolution. Use our professional PDF compressor to reduce file size quickly and securely in your browser without losing important details.", href: "/tools/compress-pdf", iconName: "Minimize2", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor online", "free pdf shrinker"] },
  { title: "PDF to Image", description: "Convert PDF pages to PNG/JPG.", seoTitle: "PDF to Image Converter - Export PDF as JPG or PNG", seoDescription: "Convert PDF pages into high-quality professional image formats like PNG and JPG instantly. Our free online converter is fast, secure, and ensures your documents are transformed with 100% clarity and zero logs.", href: "/tools/pdf-to-image", iconName: "ImageIcon", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["pdf to image", "pdf to jpg", "pdf to png", "convert pdf to jpg online", "pdf converter"] },
  { title: "Image to PDF", description: "Convert images to a PDF document.", seoTitle: "Image to PDF Converter - Create PDF from JPG/PNG", seoDescription: "Instantly convert your photos and images into a single, clean PDF document. Toollix offers a fast and secure image-to-PDF converter that supports JPG, PNG, and WebP formats for professional document creation.", href: "/tools/image-to-pdf", iconName: "FileText", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["image to pdf", "jpg to pdf", "png to pdf", "convert images to pdf", "free image converter"] },
  { title: "Word to PDF", description: "Convert Word documents to PDF exactly as they appear.", seoTitle: "Word to PDF Converter - DOCX to PDF Online", seoDescription: "Convert Word documents to PDF accurately, preserving all formatting and fonts. Our professional online converter is fast, secure, and ensures your DOCX files are transformed into perfect PDFs every time.", href: "/tools/word-to-pdf", iconName: "FileText", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["word to pdf", "convert docx to pdf", "doc to pdf", "free word to pdf converter", "high quality word converter"] },
  { title: "PDF to Word", description: "Convert PDFs into editable Word documents.", seoTitle: "PDF to Word Converter - Edit PDF in Word Online", seoDescription: "Transform any PDF into an editable Word document for quick text modifications. Our online PDF-to-Word converter is fast, secure, and maintains the original layout of your document for seamless editing in Microsoft Word.", href: "/tools/pdf-to-word", iconName: "FileText", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["pdf to word", "convert pdf to word", "pdf to docx"] },
  { title: "Sign PDF", description: "Draw, type, or upload your signature online.", seoTitle: "Sign PDF Online - Add Digital Signatures Securely", seoDescription: "Draw, type, or upload your signature to any PDF document securely. Our professional online signing tool is encrypted, fast, and works directly in your browser, making it easy to sign contracts and forms instantly.", href: "/tools/sign-pdf", iconName: "FileText", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["sign pdf", "e-sign pdf", "add signature to pdf", "pdf signer online", "free electronic signature"] },
  { title: "Edit PDF", description: "Edit PDFs: add text, images, and annotations online.", seoTitle: "Edit PDF Online - Add Text, Images & Annotations", seoDescription: "A professional PDF editor to modify text, insert images, and annotate documents online. Toollix provides a fast, secure, and easy-to-use editing suite that works directly in your browser with no installation required.", href: "/tools/edit-pdf", iconName: "Edit", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["edit pdf", "pdf annotation", "add text to pdf", "pdf editor", "online pdf edit"] },
  { title: "OCR PDF", description: "Extract text from scanned PDFs and images.", seoTitle: "Free OCR PDF - Extract Text from Scanned PDFs", seoDescription: "Convert scanned PDFs and images into editable text with high-precision OCR technology. Our online tool is fast, secure, and supports multiple languages to help you extract data from your documents with zero effort.", href: "/tools/ocr-pdf", iconName: "ScanLine", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["ocr pdf", "pdf to text", "extract text from scan", "online optical character recognition", "scanned pdf to word"] },
  { title: "PDF Booklet Arranger", description: "Re-order PDF pages for 'Saddle Stitch' booklet printing.", seoTitle: "PDF Booklet Creator - Saddle Stitch Page Arranger", seoDescription: "Re-order PDF pages for professional booklet printing. Perfect for zines and programs.", href: "/tools/pdf-to-booklet", iconName: "FileText", category: "PDF Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["pdf booklet", "booklet maker", "saddle stitch", "print zine", "pdf imposition"] },
  
  // Image Tools
  { title: "Compress Image", description: "Reduce image file size.", seoTitle: "Compress Image Online - Reduce File Size for Free", seoDescription: "Optimize and shrink JPG, PNG, and WebP images without losing visual clarity. Our free online image compressor is fast, secure, and helps you reduce file sizes for faster web performance and easier sharing.", href: "/tools/compress-image", iconName: "ImageIcon", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["compress image", "reduce image size", "shrink image", "online image compressor", "jpg compressor"] },
  { title: "Resize Image", description: "Resize images to exact pixels.", seoTitle: "Resize Image Online - Change Dimensions in Pixels", seoDescription: "Adjust the width and height of any image with precision. Ideal for web and social media.", href: "/tools/resize-image", iconName: "ImageIcon", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["resize image", "image resizer", "change image dimensions", "online photo resizer", "resize jpg/png"] },
  { title: "Crop Image", description: "Crop any region from your image.", seoTitle: "Crop Image Online - Trim & Cut Photos Easily", seoDescription: "Crop any region from your image with professional aspect ratios and precision tools.", href: "/tools/crop-image", iconName: "Scissors", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["crop image", "image cropper", "crop photo online", "free online cropper", "crop jpg"] },
  { title: "Image Converter", description: "Convert JPG, PNG, WebP.", seoTitle: "Image Converter - Convert JPG, PNG, WebP Online", seoDescription: "Fast and free conversion between popular image formats with zero quality loss.", href: "/tools/convert-image", iconName: "RefreshCw", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["image converter", "convert jpg to png", "convert png to webp", "online image format converter", "free image tool"] },
  { title: "Background Remover", description: "AI-powered one-click background removal.", seoTitle: "AI Background Remover - Remove Image BG in 1-Click", seoDescription: "Instantly remove backgrounds from any image using professional AI technology. Our background remover is clean, precise, and high-resolution, working in one click to give you perfect transparent images for any project.", href: "/tools/bg-remover", iconName: "Wand2", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["remove background", "bg remover", "ai background removal", "online bg eraser", "transparent background"] },
  { title: "Photo Enhancer", description: "Free photo filters and sharpening.", seoTitle: "Photo Enhancer - Sharpen & Filter Images Online", seoDescription: "Improve image quality, sharpen blurry details, and apply professional photo filters.", href: "/tools/photo-enhancer", iconName: "Wand2", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["photo enhancer", "sharpen image", "apply photo filters", "improve image quality online", "free photo editor"] },
  { title: "Screen-to-GIF Recorder", description: "Record your screen and convert it to GIF instantly.", seoTitle: "Screen to GIF Recorder - Capture & Convert Instantly", seoDescription: "Record your screen activity and save it as a high-quality GIF. Ideal for tutorials.", href: "/tools/screen-gif", iconName: "ImageIcon", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["screen to gif", "screen recorder", "browser gif recorder", "record gif online"] },
  { title: "Professional Passport Photo Creator", description: "Convert any portrait into a print-ready passport photo grid.", seoTitle: "Passport Photo Maker - Professional AI Photo Grid", seoDescription: "Convert any portrait into a print-ready passport photo grid with auto BG removal.", href: "/tools/passport-photo-maker", iconName: "ScanLine", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["passport photo", "id photo maker", "visa photo", "background removal", "print photo"] },
  { title: "Thumbnail Maker", description: "Create professional thumbnails with text and overlays.", seoTitle: "YouTube Thumbnail Maker - Pro Video Overlays", seoDescription: "Create high-click thumbnails with professional text, icons, and image overlays.", href: "/tools/thumbnail-maker", iconName: "ImageIcon", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["thumbnail maker", "youtube thumbnail maker", "create thumbnail"] },
  { title: "AI Image Enhancer", description: "Professional high-resolution upscaling powered by AI.", seoTitle: "AI Image Upscaler - Enhance Photo Quality & Resolution", seoDescription: "Professional AI-powered image upscaling. Increase resolution and enhance photo clarity with deep learning cloud nodes.", href: "/tools/ai-upscaler", iconName: "Zap", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", comingSoon: true, keywords: ["ai image upscaler", "enhance photo", "upscale image online", "high resolution photo"] },
  { title: "Screenshot Beautifier", description: "Transform raw screenshots into professional marketing mockups.", seoTitle: "Screenshot Beautifier - Pro Device Mockups", seoDescription: "Add padding, shadows, and rounded corners to your screenshots instantly. Create professional mockups for App Store and social media.", href: "/tools/screenshot-beautifier", iconName: "Monitor", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["screenshot beautifier", "screenshot mockup", "pro screenshots"] },
  { title: "Add Border to Image", description: "Add solid or custom borders to any photo online.", seoTitle: "Add Border to Image Online - Custom Frame Tool", seoDescription: "Add solid borders to photos. Adjust thickness and color via hex code. High-quality export with zero quality loss.", href: "/tools/add-border-to-image", iconName: "Square", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["add border to image", "image frame", "photo border"] },
  { title: "Image Inverter", description: "Invert colors of any image instantly (Negative effect).", seoTitle: "Image Inverter Online - Invert Photo Colors", seoDescription: "1-click color inversion for photos. Create negative effects or fix inverted images easily in your browser.", href: "/tools/image-inverter", iconName: "ArrowLeftRight", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["image inverter", "invert colors", "negative image"] },
  { title: "Vibe Canvas Studio", description: "Minimalist design workspace for high-intent graphics.", seoTitle: "Vibe Canvas Studio - Minimalist Design Editor", seoDescription: "A professional studio-grade design workspace. Create high-intent graphics with a canvas-to-output pipeline, featuring real-time state management and SVG injection.", href: "/tools/canvas-studio", iconName: "Palette", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-04", keywords: ["vibe canvas", "design editor", "online canvas", "minimalist design tool"] },
  { title: "Photo Merger", description: "Combine multiple photos vertically or horizontally.", seoTitle: "Photo Merger Online - Combine Photos & Create Collages", seoDescription: "Stitch multiple images together into one professional layout. Support for vertical, horizontal, and grid merging with custom spacing.", href: "/tools/combine-images-online", iconName: "Layout", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["photo merger", "combine images", "image stitcher", "photo collage"] },

  // Developer Tools
  { title: "JSON Formatter", description: "Beautify and validate JSON.", seoTitle: "JSON Formatter & Validator - Beautify JSON Code", seoDescription: "Clean, format, and validate your JSON data for better readability and debugging.", href: "/tools/json-formatter", iconName: "Code2", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["json formatter", "json beautifier", "validate json", "online json viewer", "format json"] },
  { title: "SQL Formatter", description: "Beautify and standardize SQL queries.", seoTitle: "SQL Formatter - Beautify & Standardize Queries", seoDescription: "Standardize your SQL code with professional indentation and syntax highlighting.", href: "/tools/sql-formatter", iconName: "Database", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["sql formatter", "sql beautifier", "format sql online", "syntax highlighting sql"] },
  { title: "Base64 Encoder", description: "Encode/Decode Base64 strings.", seoTitle: "Base64 Encoder & Decoder - Secure String Tool", seoDescription: "Quickly encode or decode strings to Base64. Safe, fast, and entirely browser-based.", href: "/tools/base64", iconName: "Code2", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["base64 encoder", "base64 decoder", "online base64 tool", "convert text to base64"] },
  { title: "Regex Tester", description: "Live test & debug Regex.", seoTitle: "Live Regex Tester - Debug Regular Expressions", seoDescription: "Test and debug your Regex patterns in real-time with helpful syntax highlighting.", href: "/tools/regex-tester", iconName: "Code2", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["regex tester", "regex debugger", "live regex test", "online regular expression tool"] },
  { title: "URL Encoder", description: "Encode query strings securely.", seoTitle: "URL Encoder & Decoder - Secure Query String Tool", seoDescription: "Safely encode or decode URL parameters to ensure valid and secure web links.", href: "/tools/url-encoder", iconName: "Code2", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["url encoder", "url decoder", "percent encoding", "online url tool"] },
  { title: "HTML Minifier", description: "Shrink and optimize HTML code.", seoTitle: "HTML Minifier - Optimize & Shrink Website Code", seoDescription: "Remove unnecessary characters from your HTML to improve page load speed and SEO.", href: "/tools/html-minifier", iconName: "Code2", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["html minifier", "compress html", "online html shrinker", "optimize html code"] },
  { title: "CSV to JSON", description: "Convert CSV to JSON and vice versa.", seoTitle: "CSV to JSON Converter - Simple Data Transformation", seoDescription: "Convert CSV data to JSON and vice versa instantly. Perfect for developers and data.", href: "/tools/csv-to-json", iconName: "Table", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["csv to json", "json to csv", "convert csv online", "csv converter"] },
  { title: ".env Validator", description: "Check .env syntax and flag insecure secrets.", seoTitle: ".env Validator - Secure Syntax & Secret Checker", seoDescription: "Validate .env files for syntax errors and insecure secrets. 100% private and local.", href: "/tools/env-validator", iconName: "ShieldCheck", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-13", keywords: ["env validator", "dotenv checker", "check environment variables", "secure env"] },
  { title: "JSON to TypeScript", description: "Generate TypeScript interfaces from JSON.", seoTitle: "JSON to TypeScript - Generate Interfaces Instantly", seoDescription: "Convert JSON objects into clean TypeScript interfaces for your development projects.", href: "/tools/json-to-typescript", iconName: "Code2", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-13", keywords: ["json to typescript", "json to ts", "generate ts interfaces", "typescript model generator"] },
  { title: "Cron Humanizer", description: "Build and translate cron schedule expressions.", seoTitle: "Cron Expression Descriptor - Translate Cron to Text", seoDescription: "Build and translate complex cron schedules into plain, readable English text.", href: "/tools/cron-humanizer", iconName: "Terminal", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["cron humanizer", "cron builder", "cron syntax", "cron helper", "cron format"] },
  { title: "eBook to Markdown/PDF", description: "Extract clean Markdown or PDFs from EPUB files.", seoTitle: "EPUB to Markdown Converter - Extract Clean Text", seoDescription: "Extract clean Markdown or minimalist PDFs from eBook files for Notion or reading.", href: "/tools/epub-converter", iconName: "FileText", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["epub to markdown", "convert ebook to pdf", "epub parser", "obsidian ebook", "notion epub"] },
  { title: "Strong Password Generator", description: "Create secure, random passwords.", seoTitle: "Strong Password Generator - Secure & Random Passwords", seoDescription: "Generate highly secure, random passwords with custom requirements for maximum safety. Our free online tool is fast, secure, and works entirely in your browser, ensuring your passwords are never saved.", href: "/tools/password-generator", iconName: "Lock", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["password generator", "secure password", "random password", "password maker"] },
  { title: "AI Text to Speech", description: "Convert text into natural-sounding speech.", seoTitle: "AI Text to Speech - Natural AI Voice Generator", seoDescription: "Convert written text into natural-sounding speech across multiple languages. Our AI voice generator is fast, secure, and perfect for creating audiobooks, tutorials, and accessible content online.", href: "/tools/text-to-speech", iconName: "Mic", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["text to speech", "tts", "voice generator", "speech synthesis"] },
  { title: "Lorem Ipsum Generator", description: "Generate placeholder text for your projects.", seoTitle: "Lorem Ipsum Generator - Professional Placeholder Text", seoDescription: "Generate high-quality placeholder text for your design and development projects. Our professional generator is fast, secure, and allows you to customize the length and format of your filler text.", href: "/tools/lorem-ipsum", iconName: "AlignLeft", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["lorem ipsum", "placeholder text", "filler text", "dummy text"] },
  { title: "Case Converter", description: "Instantly convert text between different cases.", seoTitle: "Text Case Converter - Uppercase, Lowercase & Title", seoDescription: "Instantly switch between UPPERCASE, lowercase, Title Case, and more for your text. Our professional online converter is fast, secure, and helps you format your content perfectly with zero effort.", href: "/tools/case-converter", iconName: "Type", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["case converter", "uppercase to lowercase", "title case", "sentence case"] },
  { title: "Split Text", description: "Split text into multiple parts using custom delimiters.", seoTitle: "Split Text Online - Split by Delimiter, Newline, or Regex", seoDescription: "Effortlessly split text into lists or columns using custom delimiters, newlines, or regular expressions. Fast, secure, and entirely browser-based.", href: "/tools/split-text", iconName: "Scissors", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["split text", "text splitter", "delimiter", "text to list"] },
  { title: "Text Reverser", description: "Reverse text, words, or lines instantly.", seoTitle: "Text Reverser Online - Flip Text, Words, and Lines", seoDescription: "Reverse your text strings, flip the order of words, or reverse lines in a document instantly. Fast and secure text reversal tool.", href: "/tools/text-reverser", iconName: "RefreshCw", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["reverse text", "flip text", "backwards text", "text reverser"] },
  { title: "Remove Extra Spaces", description: "Clean up messy text by removing duplicate spaces and tabs.", seoTitle: "Remove Extra Spaces Online - Clean & Trim Text", seoDescription: "Remove multiple spaces, tabs, and unnecessary line breaks from your text instantly for a cleaner look.", href: "/tools/remove-extra-spaces", iconName: "AlignJustify", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["remove extra spaces", "clean text", "trim whitespace", "text cleaner"] },
  { title: "Remove Duplicate Lines", description: "Instantly strip redundant lines from any list or text block.", seoTitle: "Remove Duplicate Lines Online - Clean Unique Lists", seoDescription: "Remove duplicate lines from your text or lists instantly. Fast, secure, and preserves original line order or sorts alphabetically.", href: "/tools/remove-duplicate-lines", iconName: "Scissors", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["remove duplicate lines", "unique lines", "deduplicate text", "clean list"] },
  { title: "Line Counter", description: "Count lines, words, and characters in your text.", seoTitle: "Line Counter Online - Word & Character Count Tool", seoDescription: "Fast and professional line, word, and character counter. Analyze text density and structure instantly in your browser.", href: "/tools/line-counter", iconName: "AlignJustify", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["line counter", "word count", "character counter", "text analyzer"] },
  { title: "GUID Generator", description: "Generate unique GUIDs/UUIDs for your projects.", seoTitle: "GUID Generator Online - Generate Unique UUID v4", seoDescription: "Quickly generate single or bulk unique GUIDs (UUID v4) for your development and database needs. Fast, random, and secure.", href: "/tools/guid-generator", iconName: "Fingerprint", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["guid generator", "uuid generator", "random uuid", "unique id"] },
  { title: "Slug Generator", description: "Convert text into SEO-friendly URL slugs.", seoTitle: "Slug Generator Online - SEO Friendly URL Slugs", seoDescription: "Convert titles and text into clean, SEO-friendly URL slugs instantly. Supports custom delimiters and character stripping.", href: "/tools/slug-generator", iconName: "Link", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["slug generator", "url slug", "seo slug maker", "friendly url"] },
  { title: "MD5 Hash Generator", description: "Generate secure MD5 hashes with optional salt.", seoTitle: "MD5 Hash Generator Online - Secure Hash with Salt", seoDescription: "Quickly generate MD5 hashes for strings and files. Includes support for custom salt for enhanced security. Fast, secure, and client-side.", href: "/tools/md5-hash", iconName: "ShieldCheck", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["md5 hash", "md5 generator", "string hash", "secure hash"] },
  
  // Generators
  { title: "Coin Flipper", description: "Flip a coin online for quick decisions.", seoTitle: "Online Coin Flipper - Flip a Coin Heads or Tails", seoDescription: "Flip a coin online for quick decisions. Fair, random, and visually stunning 3D-style text coin flip.", href: "/tools/flip-coin", iconName: "Coins", category: "Generators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["flip coin", "heads or tails", "coin flipper", "toss online", "coin toss"] },
  { title: "Dice Roller", description: "Roll virtual six-sided or D20 dice for games.", seoTitle: "Online Dice Roller - Virtual 3D Dice Simulator", seoDescription: "Roll single or multiple dice (D6, D20, etc.) for board games or decisions. Fair and random virtual dice simulator.", href: "/tools/dice-roller", iconName: "Dice5", category: "Generators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["dice roller", "roll dice online", "virtual dice", "random dice"] },
  { title: "Random Number Generator", description: "Generate truly random numbers within a range.", seoTitle: "Advanced Random Number Generator - Customizable RNG", seoDescription: "Generate random numbers with customizable ranges, exclude numbers, and batch results. Cryptographically secure RNG.", href: "/tools/random-number-advanced", iconName: "Hash", category: "Generators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["random number generator", "rng", "random picker", "secure random"] },
  { title: "Remove Punctuation", description: "Strip punctuation marks from any text.", seoTitle: "Remove Punctuation Online - Clean Text Symbols", seoDescription: "Effortlessly remove punctuation, symbols, and special characters from your text. Fast, secure, and preserves whitespace structure.", href: "/tools/remove-punctuation", iconName: "Scissors", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["remove punctuation", "strip symbols", "clean text", "text sanitizer"] },
  { title: "Box Shadow Generator", description: "Visually design and export CSS box-shadows.", seoTitle: "CSS Box Shadow Generator - Interactive Design Tool", seoDescription: "Create professional CSS box shadows visually with live preview. Customize blur, spread, color, and inset properties with instant CSS export.", href: "/tools/box-shadow-generator", iconName: "Palette", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["box shadow generator", "css shadow maker", "box-shadow tool", "ui design"] },
  
  // QR Tools
  { title: "QR Generator", description: "Create static & dynamic QR codes.", seoTitle: "QR Code Generator - Create Static & Dynamic QRs", seoDescription: "Generate custom QR codes for links, text, and Wi-Fi instantly. Our professional high-resolution QR generator is fast, secure, and allows you to create scannable codes for any purpose in seconds.", href: "/tools/qr-generator", iconName: "QrCode", category: "QR Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["qr generator", "create qr code", "online qr maker", "generate qr code online", "free qr generator"] },
  { title: "QR Scanner", description: "Scan QR codes with camera or image upload.", seoTitle: "Online QR Code Scanner - Scan from Camera or Image", seoDescription: "Scan QR codes instantly using your camera or by uploading an image. Our fast and secure online QR reader supports multiple formats and ensures your data is processed privately in your browser.", href: "/tools/qr-scanner", iconName: "ScanLine", category: "QR Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["qr scanner", "scan qr code", "online qr reader", "decode qr code online"] },
  { title: "QR Menu Builder", description: "Create stylish, printable QR code menu frames.", seoTitle: "QR Menu Maker for Restaurants - Custom Frames", seoDescription: "Create stylish, printable QR menus for restaurants with professional custom frames. Our builder is fast, secure, and helps you design attractive digital menus that customers can scan with ease.", href: "/tools/qr-menu", iconName: "QrCode", category: "QR Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["qr menu builder", "restaurant qr menu", "qr frame maker", "printable qr menu"] },
  
  // Color Tools
  { title: "Color Picker", description: "Extract colors from images.", seoTitle: "Online Color Picker - Extract Hex & RGB from Images", seoDescription: "Identify and extract color codes from any image with a professional eyedropper tool. Our online color picker is fast, secure, and provides HEX, RGB, and HSL values for all your design projects.", href: "/tools/color-picker", iconName: "Palette", category: "Color Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["color picker", "extract color from image", "image color eyedropper", "online color picker"] },
  { title: "Palette Generator", description: "Generate cohesive color palettes.", seoTitle: "Color Palette Generator - Create Beautiful Schemes", seoDescription: "Generate professional color palettes for your design projects instantly. Toollix provides a fast and secure palette maker that helps you create beautiful, cohesive color schemes for any website or app.", href: "/tools/palette-generator", iconName: "Palette", category: "Color Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["palette generator", "color palette maker", "generate color scheme", "online palette tool"] },
  { title: "Contrast Checker", description: "Check WCAG contrast ratio for colors.", seoTitle: "WCAG Color Contrast Checker - Accessibility Tool", seoDescription: "Check background and text color contrast to ensure web accessibility and WCAG compliance. Our professional tool is fast, secure, and helps you create inclusive designs that are easy for everyone to read.", href: "/tools/contrast-checker", iconName: "Palette", category: "Color Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["contrast checker", "wcag contrast ratio", "accessibility color checker", "online contrast tool"] },
  { title: "Gradient Generator", description: "Create and export CSS gradients.", seoTitle: "CSS Gradient Generator - Create Linear & Radial Gradients", seoDescription: "Create and export beautiful CSS gradients for your websites and UI designs. Our online generator supports linear and radial gradients, providing clean CSS code that you can copy and paste instantly.", href: "/tools/gradient-generator", iconName: "Palette", category: "Color Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["gradient generator", "css gradient maker", "create linear gradient", "online gradient tool"] },
  { title: "HEX to RGB", description: "Convert colors between formats.", seoTitle: "HEX to RGB Converter - Rapid Color Format Switching", seoDescription: "Quickly convert colors between HEX, RGB, and HSL formats with zero effort. Our professional online converter is fast, secure, and ensures your color values are accurate for all your design and dev needs.", href: "/tools/hex-rgb", iconName: "Palette", category: "Color Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", keywords: ["hex to rgb", "rgb to hex", "color converter", "convert color format online"] },
  { title: "Favicon Maker & Generator", description: "Professional favicon maker and generator.", seoTitle: "Pro Favicon Generator - Create Multi-Size Icons", seoDescription: "Generate professional .ico files, Apple Touch icons, and Android icons in seconds. Our free favicon maker is fast, secure, and ensures your website looks polished on every device and browser tab.", href: "/tools/favicon-studio", iconName: "Palette", category: "Color Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["favicon maker", "favicon generation", "ico maker", "apple touch icon", "tab icon", "free favicon creator"] },

  // Marketing Tools
  { title: "UTM Link Builder", description: "Generate tracked links for campaigns.", seoTitle: "UTM Link Builder - Generate Tracked Campaign Links", seoDescription: "Create custom UTM parameters to track marketing ads and social media performance securely. Our professional link builder is fast, secure, and helps you organize your campaign tracking with ease.", href: "/tools/utm-builder", iconName: "Link", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-13", keywords: ["utm builder", "utm generator", "track links", "marketing links", "link builder"] },
  { title: "Social Handle Checker", description: "Check brand name availability.", seoTitle: "Social Media Handle Checker - Username Availability", seoDescription: "Instantly check if your brand name is available across all major social networks. Our fast and secure handle checker helps you secure your online identity and maintain brand consistency everywhere.", href: "/tools/social-checker", iconName: "Share2", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-13", keywords: ["social handle checker", "username availability", "brand name checker", "social media search"] },
  { title: "WhatsApp Link Maker", description: "Generate shareable WhatsApp chat links.", seoTitle: "WhatsApp Link Generator - Create Chat Links & QRs", seoDescription: "Generate shareable WhatsApp chat links and QR codes to start conversations instantly. Our professional tool is fast, secure, and allows you to add custom messages to your links for better engagement.", href: "/tools/whatsapp-no-save", iconName: "MessageSquare", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-13", keywords: ["whatsapp link maker", "whatsapp generator", "message without saving", "whatsapp qr code"] },
  { title: "Brand Kit Extractor", description: "Extract colors and logos from any website.", seoTitle: "Brand Kit Extractor - Scrape Colors & Logos from URL", seoDescription: "Extract primary brand colors and logos from any website URL in one click. Our professional extractor is fast, secure, and helps you analyze the design elements of any site for inspiration or research.", href: "/tools/brand-kit", iconName: "Palette", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["brand kit extractor", "extract colors from url", "website brand scraper", "brand design tools"] },
  { title: "Thread-to-Carousel", description: "Transform text into beautiful social carousels.", seoTitle: "Thread to Carousel - Convert Text to Social Media", seoDescription: "Transform text threads into beautiful Instagram and LinkedIn carousel packs. Our professional generator is fast, secure, and helps you create engaging social media content from your written ideas.", href: "/tools/thread-to-post", iconName: "Link", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-14", keywords: ["twitter thread carousel", "instagram carousel maker", "thread to image", "carousel generator"] },
  { title: "YouTube Thumbnail Downloader", description: "Download YouTube thumbnails in high quality.", seoTitle: "YouTube Thumbnail Downloader - High-Res Exports", seoDescription: "Download high-quality YouTube thumbnails instantly by entering the video URL. Our professional downloader is fast, secure, and ensures you get the highest resolution available for your research or use.", href: "/tools/youtube-thumbnail", iconName: "Video", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["youtube thumbnail", "download thumbnail", "yt thumbnail downloader"] },
  { title: "Keyword Density Analyzer", description: "Optimize your content for SEO keywords.", seoTitle: "Keyword Density Analyzer - Optimize Content for SEO", seoDescription: "Analyze text to find frequent keywords and improve your content's search ranking. Our professional SEO tool is fast, secure, and helps you optimize your articles for better visibility in search results.", href: "/tools/keyword-density", iconName: "Activity", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-04-26", keywords: ["keyword density", "seo analyzer", "keyword count", "content optimization"] },

  // New Image & Graphics

  { title: "Image to ASCII", description: "Transform images into character-based ASCII art.", seoTitle: "Image to ASCII Art - Convert Photo to Text", seoDescription: "Transform images into character-based art for bios and terminal. Unique and creative text-based image conversion.", href: "/tools/image-to-ascii-art", iconName: "Type", category: "Image Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["image to ascii", "ascii art generator", "photo to text art"] },

  // New Text & Social Media
  { title: "Find & Replace", description: "Bulk edit text by replacing words or characters.", seoTitle: "Find and Replace Text Online - Bulk String Editor", seoDescription: "Bulk edit text. Replace words or characters with case-sensitivity. Fast and secure text replacement tool.", href: "/tools/find-and-replace-text", iconName: "Search", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["find and replace", "text editor", "bulk replace", "string editor"] },
  { title: "Emoji Remover", description: "Strip all emojis and symbols from your text.", seoTitle: "Emoji Remover - Strip Emojis from Text Online", seoDescription: "Clean text by stripping all emojis/symbols for clean data analysis. Fast and private emoji removal tool.", href: "/tools/remove-emojis-from-text", iconName: "Smile", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["emoji remover", "strip emojis", "clean text symbols"] },
  { title: "Add Prefix/Suffix", description: "Add text to the start or end of every line.", seoTitle: "Add Prefix and Suffix to Text - Line Editor", seoDescription: "Automatically add text to the start or end of every line instantly. Great for formatting lists and code.", href: "/tools/add-prefix-suffix-text", iconName: "PlusSquare", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["add prefix", "add suffix", "line editor", "text formatter"] },
  { title: "Social Text Stylizer", description: "Create unique bold/italic fonts for social media.", seoTitle: "LinkedIn & Instagram Text Formatter - Bold/Italic", seoDescription: "Create unique Unicode fonts (bold, script) for social media bios. Boost your engagement with styled text.", href: "/tools/social-media-text-stylizer", iconName: "Type", category: "Marketing Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["social media fonts", "bold text generator", "instagram fonts", "linkedin text formatter"] },
  { title: "Text Cleaner Pro", description: "Clean text by stripping extra spaces, tabs, and empty lines.", seoTitle: "Text Cleaner & Formatter - Remove Extra Spaces", seoDescription: "Strip extra spaces, tabs, and empty lines for clean formatting. Professional text sanitization tool.", href: "/tools/clean-text-online", iconName: "AlignJustify", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["text cleaner", "format text", "sanitize strings"] },

  // New Developer & Web
  { title: "Dummy Data Generator", description: "Generate random names, emails, and IPs for testing.", seoTitle: "Random Dummy Data Generator - JSON/CSV Mockup", seoDescription: "Generate random names, emails, and IPs for app testing. Export in JSON or CSV formats instantly.", href: "/tools/dummy-data-generator", iconName: "Database", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["dummy data", "mock data generator", "test data", "json mockup"] },
  { title: "Website Status Checker", description: "Check if a URL is active or down for everyone.", seoTitle: "Website Up or Down Checker - Real-Time Status", seoDescription: "Check if a URL is active or down for everyone. Fast ping tool to verify website availability.", href: "/tools/website-status-checker", iconName: "Activity", category: "Developer Tools", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["website status", "is it down", "website checker", "ping url"] },

  // New Generators & Randomizers
  { title: "Spin The Wheel", description: "Random decision maker and name picker wheel.", seoTitle: "Spin The Wheel - Random Decision & Name Picker", seoDescription: "Customizable digital wheel for giveaways and random choices. Fun and fair decision maker tool.", href: "/tools/spin-the-wheel-decider", iconName: "RefreshCw", category: "Generators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["spin the wheel", "random picker", "decision wheel", "giveaway tool"] },
  { title: "Godly Name Generator", description: "Generate unique fantasy names for RPG characters.", seoTitle: "Godly Name Generator - Epic RPG Character Names", seoDescription: "Generate unique fantasy names for gaming and creative writing. Epic and godly character names instantly.", href: "/tools/godly-name-generator", iconName: "Wand2", category: "Generators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["godly name generator", "fantasy names", "rpg names", "character names"] },

  { title: "Morse Code Translator", description: "Encode and decode text to Morse code.", seoTitle: "Morse Code Translator - Encode & Decode Text", seoDescription: "Convert text to Morse code and back with audio/visual feedback. Professional encoding tool.", href: "/tools/morse-code-translator", iconName: "Radio", category: "Generators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["morse code", "morse translator", "encode morse", "decode morse"] },

  // New Calculators & Counters
  { title: "Tally Counter", description: "Digital clicker counter with history tracking.", seoTitle: "Tally Counter Online - Digital Clicker Counter", seoDescription: "Simple digital counter with save-state and history tracking. Use it for counting anything online.", href: "/tools/online-tally-counter", iconName: "PlusSquare", category: "Calculators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["tally counter", "clicker counter", "online counter"] },
  { title: "Text Pixel Width", description: "Measure exact pixel width of text for SEO.", seoTitle: "Text Pixel Width Calculator - SEO & UI Tool", seoDescription: "Measure exact pixel width of text for Google title optimization. Ensure your titles aren't cut off.", href: "/tools/text-pixel-width", iconName: "Type", category: "Calculators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["pixel width", "text width calculator", "seo title length"] },
  { title: "Invoice Generator", description: "Create professional PDF invoices for free.", seoTitle: "Free Invoice Generator - Create Pro PDF Invoices", seoDescription: "Generate professional PDF invoices with tax and logo support. Fast, free, and secure invoice maker.", href: "/tools/invoice-generator", iconName: "FileText", category: "Calculators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["invoice generator", "free invoice", "pdf invoice maker"] },
  { title: "Aspect Ratio Calculator", description: "Calculate image and video aspect ratios.", seoTitle: "Aspect Ratio Calculator - Pixel Dimension Tool", seoDescription: "Calculate image dimensions (16:9, 4:3) for video and web. Perfect for designers and video editors.", href: "/tools/aspect-ratio-calculator", iconName: "Maximize2", category: "Calculators", bgClass: "bg-brand-red/10", borderClass: "group-hover:border-brand-red/50", createdAt: "2026-05-02", keywords: ["aspect ratio", "ratio calculator", "image dimensions"] },
];

export const CATEGORIES = [
  { label: "All Tools", value: "all", iconName: "LayoutGrid", slug: "all" },
  { label: "PDF Tools", value: "PDF Tools", iconName: "FileText", slug: "pdf" },
  { label: "Image Tools", value: "Image Tools", iconName: "Image", slug: "image" },
  { label: "Developer Tools", value: "Developer Tools", iconName: "Terminal", slug: "dev" },
  { label: "QR Code", value: "QR Tools", iconName: "QrCode", slug: "qr" },
  { label: "Color & Design", value: "Color Tools", iconName: "Palette", slug: "color" },
  { label: "Marketing", value: "Marketing Tools", iconName: "Link", slug: "marketing" },
  { label: "Generators", value: "Generators", iconName: "Zap", slug: "generators" },
  { label: "Calculators", value: "Calculators", iconName: "Hash", slug: "calculators" },
];
